// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Editor: typeof import('./src/components/Editor.vue')['default']
    MarkdownUploader: typeof import('./src/components/MarkdownUploader.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NModal: typeof import('naive-ui')['NModal']
    NP: typeof import('naive-ui')['NP']
    NPopselect: typeof import('naive-ui')['NPopselect']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NText: typeof import('naive-ui')['NText']
    NUpload: typeof import('naive-ui')['NUpload']
    NUploadDragger: typeof import('naive-ui')['NUploadDragger']
    NUploadm: typeof import('naive-ui')['NUploadm']
    Preview: typeof import('./src/components/Preview.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
  }
}
