// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Editor: typeof import('./src/components/Editor.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NPopselect: typeof import('naive-ui')['NPopselect']
    Preview: typeof import('./src/components/Preview.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
  }
}
